name: cct
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - crest
  - xtb
  - libgfortran=14.2.0
  - click
  - rdkit
  - tblite-python>=0.4.0
  - tblite>=0.4.0
  - jupyter
  - nwchem
  - openbabel
  - freesasa
  - pip:
    - torch
    - torchani
    - torch_geometric
    - fairchem-core
    - e3nn
    - wget
    - pymsym
    - datamol
    - p_tqdm
    - ray
    - git+https://github.com/isayevlab/aimnetcentral.git
    # - torch_scatter
    # - mace_torch==0.3.12


